// <auto-generated />
using System;
using Honzel_Family_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Honzel_Family_Website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.IngredientModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("RecipeModelID")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RecipeModelID");

                    b.ToTable("IngredientModel");
                });

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.InstructionModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RecipeModelID");

                    b.ToTable("InstructionModel");
                });

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.QuisineModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RecipeModelID");

                    b.ToTable("QuisineModel");
                });

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.RecipeModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("RecipeModel");
                });

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.IngredientModel", b =>
                {
                    b.HasOne("Honzel_Family_Website.Models.Recipe.RecipeModel", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeModelID");
                });

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.InstructionModel", b =>
                {
                    b.HasOne("Honzel_Family_Website.Models.Recipe.RecipeModel", null)
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeModelID");
                });

            modelBuilder.Entity("Honzel_Family_Website.Models.Recipe.QuisineModel", b =>
                {
                    b.HasOne("Honzel_Family_Website.Models.Recipe.RecipeModel", null)
                        .WithMany("Quisine")
                        .HasForeignKey("RecipeModelID");
                });
#pragma warning restore 612, 618
        }
    }
}
